/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Accidents: () => import('#controllers/accidents_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Exports: () => import('#controllers/exports_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
